version: '2'
services:
  # db:
  #   image: postgres
  #   ports:
  #     - 5434:5432

  app:
    build: .
    command: bundle exec rails s -p 3010 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3010:3010
    # links:
    #   - db